### ISSUE TITLE
How to get a correction image

### ISSUE THREAD

**Issue by Juddd** [kokerf/imageAlign#1]
Confusion,I note your `forwardAdditiveImageAlign` is `Void`.So after your transform. How to get the result image?

Actually I want to align this two image

[First image](https://i.stack.imgur.com/IOGGX.jpg)

[Second image](https://i.stack.imgur.com/5QZ4N.jpg)

Is possible by your method?

**Comment by kokerf** [comment]
Hi @Juddd 
I have changed the code, and you can just follow the [test/test_imageAligen.cpp](https://github.com/kokerf/imageAlign/blob/master/test/test_imageAlign.cpp#L100) file, and use the function  `warpAffineback` to warp the image.
For aligning two big images, it maybe time-consuming. I suggest you sampling some patches for alignment.
